import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { Toaster } from "@/components/ui/toaster";
import AuthProvider from "@/components/Providers/AuthProvider";
import IsAuthenticated from "@/components/IsAuthenticated";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head />
      <body>
        <AuthProvider>
          <IsAuthenticated>{children}</IsAuthenticated>
        </AuthProvider>
        <Toaster />
      </body>
    </html>
  );
}
